#!/bin/bash -el

THIS_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd ${THIS_SCRIPT_DIR}

source Docker/build.env

show_help="false"
start="false"
stop="false"
logs="false"

if [[ ${#@} -lt 1 ]]; then
  show_help="true"
fi

for arg in $@
do
  case $arg in
    "--logs"      )  logs="true"; shift;;
    "--start"     )  start="true"; shift;;
    "--stop"     )  stop="true"; shift;;
    "-h" | "--help"    )  show_help="true"; shift;;
  esac
done

if [[ "${show_help}" == "true" ]]; then
  echo "Usage: ${0} --start   Starts the container. Takes place before a --stop."
  echo "       ${0} --stop   Stops and deletes the container"
  echo "       ${0} --logs   run 'docker logs' for the container"

  exit 0
fi

if [[ ${start} == "true" ]]; then
  docker run -d --rm -p ${HOST_JENKINS_PORT}:${CONTAINER_JENKINS_PORT} --name ${CONTAINER_SHORT_NAME} ${IMAGE_TAG}:${IMAGE_VERSION}
  echo "http://localhost:${HOST_JENKINS_PORT}"
fi


if [[ ${stop} == "true" ]]; then
  docker container stop ${CONTAINER_SHORT_NAME}
fi

if [[ ${logs} == "true" ]]; then
  docker logs -f ${CONTAINER_SHORT_NAME}
fi
