#!/bin/bash

set -e

THIS_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd ${THIS_SCRIPT_DIR}

source build.env

NAME=$(basename $0)

function usage() {
  cat <<EOS
  Usage: ${NAME} - builds the container
  Arguments:
    -v -- Version number to tag the build with. Defaults to latest.
EOS
}

for arg in $@
do
  case $arg in
    "-v"               )  shift; VERSION=$1; shift;;
    "-h" | "--help"    )  HELP="true"; shift;;
  esac
done

if [ ! -z "${HELP}" ]; then
  echo $(usage)
  exit 0
fi

docker build -t "${IMAGE_TAG}:${IMAGE_VERSION}" .

