---

- name: Install python docker module for this thing
  pip:
    executable: pip3
    name: docker

- name: start docker container
  docker_container:
    name: jinkies
    image: jamandbees/jinkies:latest
    memory: 4G
    published_ports:
      - 9080:8080
    state: started
