---

- name: Upgrade the universe
  apt:
    upgrade: full
  when: ansible_facts['distribution'] == "Debian"

- name: Be shell friendly
  lineinfile:
    line: 'export TERM=xterm'
    path: '/etc/environment'

- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg', 'lsb-release', 'pipenv']
  when: ansible_facts['distribution'] == "Debian"

- name: Add Docker GPG apt Key
  shell: 'curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/trusted.gpg.d/docker-archive-keyring.gpg'
  args:
    creates: "/etc/apt/trusted.gpg.d/docker-archive-keyring.gpg"
  when: ansible_facts['distribution'] == "Debian"

- name: Add Docker Repository
  shell: >
     echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/trusted.gpg.d/docker-archive-keyring.gpg] https://download.docker.com/linux/debian 
     $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list
  when: ansible_facts['distribution'] == "Debian"

- name: Update apt and install docker-ce
  apt: update_cache=yes name={{ item }} state=latest
  loop: ['docker-ce', 'docker-ce-cli', 'containerd.io']

- name: Add admin user to docker group for ease of ease
  user:
    name: admin
    groups: docker
    append: yes
