---

credentials:
  system:
    domainCredentials:
    - credentials:
      - string:
          description: "secret-description"
          id: "secret-ID"
          scope: GLOBAL
          secret: "secret goes here"